# Generated by Django 5.2.6 on 2025-09-11 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
    ]
